# Generated by Django 3.2.18 on 2023-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230502_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='content',
            field=models.CharField(max_length=200, verbose_name='대댓글'),
        ),
    ]
