# Generated by Django 3.2.18 on 2023-05-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230502_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
